<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>kynicond</groupId>
        <artifactId>BPtesting</artifactId>
        <version>1.2</version>
    </parent>

    <artifactId>sub-moduleB</artifactId>

    <properties>
        <maven.compiler.source>20</maven.compiler.source>
        <maven.compiler.target>20</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>
        <dependency>
            <groupId>kynicond</groupId>
            <artifactId>sub-moduleA</artifactId>
            <version>1.9.6</version>   <!-- TODO Zde dat nizsi verzi-->
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>kynicond</groupId>
            <artifactId>sub-moduleC</artifactId>
            <version>1.2.3</version>   <!-- TODO Zde dat nizsi verzi-->
            <type>pom</type>
        </dependency>
    </dependencies>

</project>